### ISSUE TITLE
PH-S032: False-positive when throwing an exception within try-catch

### ISSUE THREAD

**Issue by SonnyX** [Concurrency-Lab/ParallelHelper#108]
The following method gives warning `PH_S032`, although the error can never bubble up to the caller due to the catch clause:
```csharp
    protected override Task<MyResult> MyMethodAsync()
    {
        MyResult result;
        // Set up some stuff here
        try
        {
            // Code that can throw an exception goes here
            if (myConditionIsTrue)
            {
                throw new MyConditionIsTrueException();
            }

            // No exception occurred
            result = new MyResult("Success");
        }
        catch (Exception e)
        {
            result = new MyResult($"Failure {e.Message}");
        }
        return Task.FromResult(result);
    }
```
Expected behavior would be that the warning is suppressed due to the catch clause being present, and in case the catch clause has a `throw`, that it would give the warning there.

I can imagine this is difficult to circumvent, and if so, then a simple `Won't fix` will be perfectly acceptable, however I thought it would be good to document this scenario none-the-less for future developers coming across this warning.

**Comment by camrein** [comment]
Thanks a lot for reporting this. I've created a test case inside ParallelHelper's test suite to reproduce this issue.
Fixing this is possible. Because I want to do it right (not just a general check for `Exception`) it'll take some extra time because I have to change how this analyzer works (from LINQ to Visitor to track the enclosing exception handler).
