### ISSUE TITLE
False Positive for PH_S025 - Unused Synchronous Task Result

### ISSUE THREAD

**Issue by markusschaber** [Concurrency-Lab/ParallelHelper#57]
Hi,
I think I found a false positive for PH_S025.

```
namespace ParallelHelperBug
{
    using System.Threading.Tasks;
    using FakeItEasy;
    using Xunit;

    public interface IFoo
    {
        Task<int> FooAsync(int bar);
    }

    public class UnitTest1
    {
        private readonly IFoo _foo = A.Fake<IFoo>();

        [Fact]
        public async Task Test1()
        {
            A.CallTo(() => _foo.FooAsync(42))
                .ReturnsLazily(call =>
                {
                    int twice = call.GetArgument<int>(0) * 2;
                    return Task.FromResult(twice);
                });

            var result = await _foo.FooAsync(42);
            Assert.Equal(84,result);
            A.CallTo(() => _foo.FooAsync(42)).MustHaveHappened();
        }
    }
}
```

It gives a PH_S025 warning in the line `return Task.FromResult(twice)`. I guess it's mislead by the return type `Task` of the method `Test1()` - however, the actual context of the `return` statement is the anonymous delegate passed to `ReturnsLazily`.

(This example uses xUnit and FakeItEasy, it's condensed down from a real (more complex) actual test case.)

**Comment by camrein** [comment]
Hello

Thank you very much for your issue report. I managed to concise your example a little more:
```cs
    public async Task Test() {
      Func<Task<int>> test = () => {
        return Task.FromResult(1);
      };
    }
```
Somehow I missed updating this analyzer with the new mechanism to respect activation frames. Anyway, I have fixed the analyzer accordingly.

PS: I have also noticed that the analyzer is unnecessarily restricted to only analyze method-declarations. I think I will expand it to lambdas and delegates as well.

**Comment by markusschaber** [comment]
Yes, that's really concise. 😳
Thank you for the quick fix!

**Comment by markusschaber** [comment]
Btw, is this tracker also a good place to file feature suggestions?

**Comment by camrein** [comment]
Side-note: Since I first want to use the current version a little bit to ensure no major bugs such as crashes with every little change, I'll probably delay the update until the end of the next week. In case you're eager to use this version (although you'd need to manually update it afterward if I include another change in this version), you can grab it from the [build server](https://ci.appveyor.com/project/camrein/parallelhelper/branch/master/artifacts).

Feel free to post your suggestions here. Since I couldn't identify new patterns with the last few code reviews I did, I am more than happy about any additional input. But please mind the design goal of Parallel Helper: Simple but effective analyzers. There are some exceptions, such as [PH_B009](https://github.com/Concurrency-Lab/ParallelHelper/blob/master/doc/analyzers/PH_B009.md) and [PH_B010](https://github.com/Concurrency-Lab/ParallelHelper/blob/master/doc/analyzers/PH_B010.md] - that's why they are more prone to false positives than the other analyzers. However, my observation so far was that there is usually something fishy, especially if they're triggered extensively. So please don't be disappointed if I won't include your suggestions.

Since the actual issue is resolved, I am closing this thread.
