### ISSUE TITLE
Exceptions from PH_S019 for EF Core: Do not prefer Async() Methods

### ISSUE THREAD

**Issue by markusschaber** [Concurrency-Lab/ParallelHelper#64]
Some EF Core classes like DBSet and DBContext have Method pairs like Add()/AddAsync() or AddRange()/AddRangeAsync() where the documentation states that the non-Async method should be usually preferred:

https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbcontext.addasync?view=efcore-5.0

https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbset-1.addrangeasync?view=efcore-5.0

I'm not sure how easy it is to globally exempt those specific methods from the general "prefer Async()" rule.

**Comment by camrein** [comment]
Nice catch, thank you. I was already thinking about adding a configuration feature to exclude certain types and methods from reports. For example, it's rather uncommon to add a cancellation token to `Task.Run`, since the cancellation only has an effect if the task hasn't started yet.
However, the use of `AddAsync` and its fellows shouldn't be suggested in this case (at least not by default). Maybe I'll add a hard-coded version in the meantime and change it later to a configurable one.

**Comment by markusschaber** [comment]
A similar case is Json serialization. System.Text.Json has convenient non-async overloads to serialize to a string, or deserialize from a string or ReadOnlySpan, while the ...Async() methods only work for streams (which makes sense, as serializing into a string is purely CPU bound, with no external I/O).

https://docs.microsoft.com/de-de/dotnet/api/system.text.json.jsonserializer.serialize
https://docs.microsoft.com/de-de/dotnet/api/system.text.json.jsonserializer.deserialize

**Comment by camrein** [comment]
I've extended the initial draft to make the method exclusions configurable (see [PH_S019](https://github.com/Concurrency-Lab/ParallelHelper/blob/master/doc/analyzers/PH_S019.md) for an example). However, I've opted not to include the `JsonSerializer` methods in the default exclusions. It's probably necessary to further consider the candidate resolution for async counterparts, e.g., check how similar the signatures are. But this may lead to missed true positives. Therefore, I think the configuration possibility is a fair solution for the moment.

**Comment by markusschaber** [comment]
Yes. I think it may be necessary to suppress based on the concrete method signature, not only the name, to cleanly handle the JsonSerializer case.

While I understand the Serialize to String, and SerializeAsync into Streams, I'm unsure about the overloads which take an Utf8JsonWriter, which has mostly sync methods, with the exception of DisposeAsync() and FlushAsync(), altough Utf8JsonWriter can wrap a Stream.

**Comment by camrein** [comment]
I'll leave the signature/parameter matching for a later release. With the possibility to specify how many parameters should of the same type, I suppose that users will have enough freedom to tweak this analyzer to the optimum.

That's indeed a strange type. However, that shouldn't affect this analyzer since it won't report missed Async methods if there aren't any.

**Comment by markusschaber** [comment]
Thank you for your great work!
I'm eager to use the next release.

**Comment by camrein** [comment]
Thank you very much for your inputs and support. I have released v3.1.0 on NuGet and VS Marketplace.

I am closing this issue since I have opened a new issue for the signature matching in #66.
